import = [
    "~/.config/alacritty/themes/hyper.toml"
]

[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[colors.primary]
foreground = "#FFFFFF"
background = "#000000"
