import = [
    "~/.config/alacritty/themes/hyper.toml"
]
[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[colors.primary]
foreground = "#FFFFFF"
background = "#000000"

[window]
dynamic_title = true
opacity=0.5

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
   { key = "l", mods = "Control", chars = "\ntput reset\n" }
   #{ key = "p", mods = "Control", command = { program = "tput", args = ["reset"] } }
]
